package com.rs.game.content.quests.gunnarsground.utils

import com.rs.lib.game.Item

// Quest Stages
const val STAGE_UNSTARTED = 0
const val STAGE_RECEIVED_LOVE_POEM = 1
const val STAGE_RECEIVED_RING = 2
const val STAGE_NEED_TO_CHISEL_RING = 3
const val STAGE_CHISELED_RING = 4
const val STAGE_NEED_TO_DELIVER_RING = 5
const val STAGE_NEED_TO_TALK_TO_GUNTHOR = 6
const val STAGE_RETURN_TO_GUDRUN_AFTER_GUNTHOR = 7
const val STAGE_RETURN_TO_DORORAN_TO_WRITE_POEM = 8
const val STAGE_WRITING_THE_POEM = 9
const val STAGE_FINISHED_WRITING_POEM = 10
const val STAGE_RECEIVED_GUNNARS_GROUND_POEM = 11
const val STAGE_POST_CUTSCENES = 12
const val STAGE_COMPLETE = 13

// Items
val RING_FROM_JEFFERY = Item(19770)
val DORORANS_ENGRAVED_RING = Item(19771)
val GUNNARS_GROUND_POEM = Item(19772)
val LOVE_POEM = Item(19774)
val CHISEL = Item(1755)
val SWANKY_BOOTS = Item(19776)
val ANTIQUE_LAMP = Item(19775)

// NPCs
const val JEFFERY = 637
const val QUESTING_DORORAN = 1168
const val CUTSCENE_DORORAN = 2863
const val DORORAN_POST_CUTSCENE = 2646
const val QUESTING_GUDRUN = 2864
const val CUTSCENE_GUDRUN = 2871
const val GUDRUN_POST_CUTSCENE = 2866
const val QUESTING_CHIEFTAIN_GUNTHOR = 2876
const val CUTSCENE_CHIEFTAIN_GUNTHOR = 3089
const val QUESTING_KJELL = 2873
const val CUTSCENE_KJELL = 2875
const val QUESTING_HAAKON = 3090
const val CUTSCENE_HAAKON = 3091

// Animations
const val ANIM_CHIEFTAIN_SPEECH = 14734
const val ANIM_HAAKON_CHEER = 14739
const val ANIM_KJELL_CHEER = 1531
const val ANIM_DORORAN_LISTENING = 14725
const val ANIM_PLAYER_LISTENING = 14724
const val ANIM_REASSURE_DORORAN = 6709
const val ANIM_CHISEL_RING = 14736
const val ANIM_GIVE_ITEM = 14737
const val ANIM_TAKE_ITEM = 14738

// Varbits
const val BARB_VILLAGE_VARBIT = 5819
const val DORORAN_BARB_VILLAGE_VARBIT = 5820
const val DORORAN_PRE_COMPLETE_BARB_VILLAGE_VARBIT = 8242
const val DORORAN_VARROCK_VARBIT = 6665
const val GUDRUN_BARB_VILLAGE_VARBIT = 6664
const val GUDRUN_PRE_COMPLETE_BARB_VILLAGE_VARBIT = 8243
const val GUDRUN_VARROCK_VARBIT = 6666

// Music & Sounds
const val GUNNARSGRUNN_MUSIC_ID = 896
const val CUTSCENE_HUG_MUSIC_ID = 897
const val CUTSCENE_MUSIC_ID = 898
