package com.rs.game.content.quests.gunnarsground.utils

import com.rs.lib.game.Item

const val STAGE_UNSTARTED = 0
const val STAGE_RECEIVED_LOVE_POEM = 1
const val STAGE_RECEIVED_RING = 2
const val STAGE_NEED_TO_CHISEL_RING = 3
const val STAGE_CHISELED_RING = 4
const val STAGE_NEED_TO_DELIVER_RING = 5
const val STAGE_NEED_TO_TALK_TO_GUNTHOR = 6
const val STAGE_RETURN_TO_GUDRUN_AFTER_GUNTHOR = 7
const val STAGE_RETURN_TO_DORORAN_TO_WRITE_POEM = 8
const val STAGE_WRITING_THE_POEM = 9
const val STAGE_FINISHED_WRITING_POEM = 10
const val STAGE_RECEIVED_GUNNARS_GROUND_POEM = 11
const val STAGE_POST_CUTSCENES = 12
const val STAGE_COMPLETE = 13

val RING_FROM_JEFFERY = Item(19770)
val DORORANS_ENGRAVED_RING = Item(19771)
val GUNNARS_GROUND_POEM = Item(19772)
val LOVE_POEM = Item(19774)
val CHISEL = Item(1755)

const val JEFFERY = 637
const val DORORAN_QUESTING = 1168
const val STANDING_DORORAN = 2647
const val DORORAN_POST_CUTSCENE = 2646
const val GUDRUN_QUESTING = 2864
const val GUDRUN_POST_CUTSCENE = 2866
const val CHIEFTAIN_GUNTHOR = 2876
const val KJELL = 2872
const val HAAKON = 3090

const val ANIM_CHIEFTAIN_SPEECH = 14734
const val ANIM_HAAKON_CHEER = 14739
const val ANIM_KJELL_CHEER = 1531
const val ANIM_REASSURE_DORORAN = 6709
const val ANIM_CHISEL_RING = 14736
const val ANIM_GIVE_ITEM = 14737
const val ANIM_TAKE_ITEM = 14738

const val BARB_VILLAGE_VARBIT = 5819
const val DORORAN_BARB_VILLAGE_VARBIT = 5820
const val DORORAN_PRE_COMPLETE_BARB_VILLAGE_VARBIT = 8242
const val DORORAN_VARROCK_VARBIT = 6665
const val GUDRUN_BARB_VILLAGE_VARBIT = 6664
const val GUDRUN_PRE_COMPLETE_BARB_VILLAGE_VARBIT = 8243
const val GUDRUN_VARROCK_VARBIT = 6666
